version: "3.7"

services:
  postgres-9-6:
    container_name: postgresql-9-6
    image: postgres:9.6
    env_file:
      - ./postgresql.env
    environment:
      - PGPORT=5496
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - pgdata-9-6:/var/lib/postgresql/9.6/data
    ports:
      - "5496:5496"
    networks:
      - postgres--network

  postgres-10:
    container_name: postgresql-10
    image: postgres:10
    env_file:
      - ./postgresql.env
    environment:
      - PGPORT=5410
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - pgdata-10:/var/lib/postgresql/10/data
    ports:
      - "5410:5410"
    networks:
      - postgres--network

  postgres-11:
    container_name: postgresql-11
    image: postgres:11
    env_file:
      - ./postgresql.env
    environment:
      - PGPORT=5411
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - pgdata-11:/var/lib/postgresql/11/data
    ports:
      - "5411:5411"
    networks:
      - postgres--network

networks:
  postgres--network:
    driver: bridge

volumes:
  pgdata-9-6:
  pgdata-10:
  pgdata-11: